[project]
name = "pydantic-ai-walkthrough"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dotenv>=0.9.9",
    "logfire>=3.21.1",
    "nest-asyncio>=1.6.0",
    "requests>=2.32.4",
]
